### ISSUE TITLE
ca-certificates is either missing or outdated, causing pip install to fail when using git urls.

### ISSUE THREAD

**Issue by jonparrott** [GoogleCloudPlatform/python-docker#10]
If you use a git+https url in your requirements.txt, for example:

```
-e git+https://github.com/GoogleCloudPlatform/gcloud-python.git#egg=gcloud
```

Then building the image will fail because pip can't verify the cert from github. It appears the root of this problem is ca-certificates is missing or invalid. Updating these fixes the problem.

**Comment by waprin** [comment]
:+1:

**Comment by jonparrott** [comment]
Or maybe this issue should belong over at https://github.com/GoogleCloudPlatform/debian-docker ?

**Comment by jonparrott** [comment]
This is resolved.
