### ISSUE TITLE
Invalid base image name "gcr.io/google_appengine/python"

### ISSUE THREAD

**Issue by erichiggins** [GoogleCloudPlatform/python-docker#14]
This repo recommends using `FROM gcr.io/google_appengine/python` as the base Docker image when running a custom-images on Managed VMs, but it no longer works.

[According to the documentation](https://cloud.google.com/appengine/docs/managed-vms/custom-runtimes#base_images), custom images should use `FROM gcr.io/google_appengine/python-compat` as the base image.

FWIW: The Dockerfile in this repo provides environment variables and dependencies which `python-compat` does not. That base image does not appear to have a publicly-available Dockerfile in which developers can determine the differences. It'd be helpful to have all of this cleared up.

See this SO discussion for more info:
http://stackoverflow.com/questions/34169058/google-managed-vm-module-stuck-in-reboot-loop

**Comment by jonparrott** [comment]
This is mostly a documentation issue, and I will update the docs to reflect this. 

> This repo recommends using FROM gcr.io/google_appengine/python as the base Docker image when running a custom-images on Managed VMs, but it no longer works.

This does indeed work:

```
$ docker pull gcr.io/google_appengine/python
latest: Pulling from google_appengine/python

4fe4eff7c8e7: Pull complete
f45355bf394e: Pull complete
9ab8f3f784c4: Pull complete
d95cba309c30: Pull complete
c081edf932b3: Pull complete
9ae8867732d0: Pull complete
cd1fac2bc8c3: Pull complete
7d23c019069c: Pull complete
0c3783a4c642: Pull complete
Digest: sha256:a969440799f67082444f40b1cd327dffcd6a7187f70bb838176f7a3b941efa51
Status: Downloaded newer image for gcr.io/google_appengine/python:latest
```

This image is used extensively in [getting-started-python](https://github.com/GoogleCloudPlatform/getting-started-python). If you're having issues pulling the image, we can look into it but it should work.

> According to the documentation, custom images should use FROM gcr.io/google_appengine/python-compat as the base image.

This is only the case if you need the `google.appengine.*` APIs. This runtime is a "vanilla" runtime and is intended to be used with [gcloud-python](https://github.com/GoogleCloudPlatform/gcoud-python) and is also designed to support installation of the top 100 Python packages.

> That base image does not appear to have a publicly-available Dockerfile in which developers can determine the differences. It'd be helpful to have all of this cleared up.

That is correct, however, the newer compat runtime source is available [here](https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime). In terms of what's available in the current version and this version, it's basically the same (by design).

> It'd be helpful to have all of this cleared up.

I'll update the docs to add this image as one of the images that do not contain App Engine APIs. Is there anything else I can do to help?

**Comment by erichiggins** [comment]
@jonparrott Thanks, this is a really helpful clarification.

In general, it's challenging to match up Dockerfiles to image names that live outside of the official Docker Hub. This is especially true for Google's Container Registry, which does not appear to be browseable or searchable. It may help to clarify within the README and/or Dockerfile itself which image is being defined.

I'd be curious to know why my Managed VM instance had difficulty pulling the `google_appengine/python` image, but given that the documentation suggest the use of `python-compat`, I'll chalk it up to user-error for now.

> That is correct, however, the newer compat runtime source is available here. In terms of what's available in the current version and this version, it's basically the same (by design).

Can you clarify what you mean by "newer"? Future, perhaps? When I pull `google_appengine/python-compat:latest` today, which Dockerfile/repo is used? The use of version tags (which Docker supports) may help with this sort of issue, even in the beta period.

**Comment by dt-rush** [comment]
I'm seeing the following for now: 
```
$ curl -v -L gcr.io/google_appengine/python

* Hostname was NOT found in DNS cache
*   Trying 74.125.202.82...
* Connected to gcr.io (74.125.202.82) port 80 (#0)
> GET /google_appengine/python HTTP/1.1
> User-Agent: curl/7.35.0
> Host: gcr.io
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Location: https://gcr.io/google_appengine/python
< Date: Fri, 11 Dec 2015 14:24:50 GMT
< Content-Type: text/html; charset=UTF-8
* Server Docker Registry is not blacklisted
< Server: Docker Registry
< Content-Length: 235
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< 
* Ignoring the response-body
* Connection #0 to host gcr.io left intact
* Issue another request to this URL: 'https://gcr.io/google_appengine/python'
* Found bundle for host gcr.io: 0x940950
* Hostname was NOT found in DNS cache
*   Trying 74.125.202.82...
* Connected to gcr.io (74.125.202.82) port 443 (#1)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: C=US; ST=California; L=Mountain View; O=Google Inc; CN=*.googlecode.com
*        start date: 2015-12-02 14:40:36 GMT
*        expire date: 2016-03-01 00:00:00 GMT
*        subjectAltName: gcr.io matched
*        issuer: C=US; O=Google Inc; CN=Google Internet Authority G2
*        SSL certificate verify ok.
> GET /google_appengine/python HTTP/1.1
> User-Agent: curl/7.35.0
> Host: gcr.io
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Date: Fri, 11 Dec 2015 14:24:50 GMT
< Content-Type: text/html; charset=UTF-8
* Server Docker Registry is not blacklisted
< Server: Docker Registry
< Content-Length: 1584
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: SAMEORIGIN
< Alternate-Protocol: 443:quic,p=0
< Alt-Svc: clear
< 
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/google_appengine/python</code> was not found on this server.  <ins>That’s all we know.</ins>
* Connection #1 to host gcr.io left intact
```

**Comment by jonparrott** [comment]
You typically can't curl ``gcr.io``. Try a `docker pull`.

**Comment by jonparrott** [comment]
> In general, it's challenging to match up Dockerfiles to image names that live outside of the official Docker Hub. This is especially true for Google's Container Registry, which does not appear to be browseable or searchable. It may help to clarify within the README and/or Dockerfile itself which image is being defined.

We are trying to ensure that every dockerfile that uses a `gcr.io` image links to the github repo, see [here](https://github.com/GoogleCloudPlatform/getting-started-python/blob/master/1-hello-world/Dockerfile#L19). If you see any samples without a link, please feel free to ping me.

> Can you clarify what you mean by "newer"? Future, perhaps? When I pull google_appengine/python-compat:latest today, which Dockerfile/repo is used? The use of version tags (which Docker supports) may help with this sort of issue, even in the beta period.

The current `python-compat` version is limited to using one core. The multicore runtime is mostly the same, just supports running one process for each core. @andrewsg can give more info.

**Comment by dt-rush** [comment]
Hey @jonparrott, 

Do you mean to suggest that /python is the multicore runtime? Is any of this documented anywhere?

**Comment by jonparrott** [comment]
@dt-rush the /python runtime is this image, which is gunicorn with one sync worker per core by default.

**Comment by jonparrott** [comment]
Correction, it defaults to one worker, but you set the `CMD` yourself so you can specify the worker type and number.

**Comment by dt-rush** [comment]
Ah, thank you, it's all here. Is the python-compat image also available on github?

**Comment by jonparrott** [comment]
@dt-rush 

Not presently, to summarize there are 3 Managed VMs runtimes presently for Python:

* `gcr.io/google_appengine/python`, A 'vanilla' python runtime, which is this repository.
* `gcr.io/google_appengine/python-compat`, the current image used when specifying `runtime: python27` on managed vms. This is not open source, and we do not plan to open-source it at this time because...
* The `python-compat` image will be replaced with [appengine-python-vm-runtime](https://github.com/GoogleCloudPlatform/appengine-python-vm-runtime) which is mostly identical to the `python-compat` image except it can handle more than one request concurrently.

We're aware this is complicated. Once `appengine-python-vm-runtime` replaces `python-compat` it'll be a more straightforward story. For now, use `python` if you don't need any appengine APIs or can use [gcloud-python](https://github.com/GoogleCloudPlatform/gcloud-python) and use `python-compat/appengine-python-vm-runtime` if you need app engine APIs.
