### ISSUE TITLE
Question: Unable to install psycopg2

### ISSUE THREAD

**Issue by rockymeza** [GoogleCloudPlatform/python-docker#7]
Hi again,

I had another question.  I was trying to get Django up and running on the python-runtime image and I ran into an issue getting it working.  I was planning on using postgres as my database, which means I need to install the psycopg2 python package, but the psycopg2 package relies on libpq-dev which I need to install using apt-get.  So I thought I could just add a RUN statement to my Dockerfile and install the libpq-dev package, but that doesn't work because of the ONBUILD statements on the python-runtime image run before any of my statements run.

Dockerfile:

```docker
FROM google/python-runtime

RUN apt-get install libpq-dev
```

This will error during the pip install requirements.txt line.

Is this possible to do with the python-runtime image or should I just drop down into the google/python image and copy what I need from the python-runtime image?

Thanks,

**Comment by jonparrott** [comment]
This should be resolved. Please feel free to re-open it if it doesn't work.
